### ISSUE TITLE
Stabilisation of the computational mode due to L2 temperature discretisation

### ISSUE THREAD

**Issue by davelee2804** [davelee2804/tsw_eigs#2]
Discretising the potential temperature on the L2 space (the _Lorenz_ grid) leads to a computational mode where a `2dz` oscillation cannot be controlled, as described here:
https://journals.ametsoc.org/view/journals/mwre/124/3/1520-0493_1996_124_0511_vdotpe_2_0_co_2.xml?tab_body=pdf

This mode is not readily observed in the `\theta` field (at least for the warm bubble test case), but is observed for the other fields, such as the potential vorticiy, as in the attached at time step 100 (400s)

Potential means of suppressing this term include:

1. the application of an interior penalty term for `\theta` jumps in the `\Theta` equation of the form `\int |F\cdot n_\Gamma|*jump(s)*jump(\theta)d\Gamma` (for test function `s`). This is proved to dissipate tracer variance, `\rho\theta^2`, and has been implemented in the revised `\Theta` residual here: https://github.com/davelee2804/tsw_eigs/commit/6c9fd47e6a3577270ea159770a90564a1793b3fc 
but does not seem to be having any effect. Either it is implemented incorrectly, or tracer variance is not related to the problem

2. Upwind the diagnostic equations for `q` or `\theta` using SUPG for a H1 representation of these variables (not implemented yet)

![theta_dt400s](https://github.com/davelee2804/tsw_eigs/assets/11448075/06166c6b-8aef-4d3f-b50f-eb7c6b6c1405)
![vort_dt400s](https://github.com/davelee2804/tsw_eigs/assets/11448075/2d6aa378-0c6f-48ed-8be4-605484cab8e1)

**Comment by davelee2804** [comment]
Since I'm not sure about the implementation of the interior penalty term in the `F_\Theta_up()` function here: https://github.com/davelee2804/tsw_eigs/commit/6c9fd47e6a3577270ea159770a90564a1793b3fc
I tried an alternative implementation as:
`∫(0.5*dt*mean(abs(F⋅n_Γ))*jump(q)*jump(θ))dΓ`
which resulted in the error:
`│    MethodError: no method matching abs(::Gridap.Geometry.SkeletonPair{GridapDistributed.DistributedCellField{MPIArray{Gridap.CellData.OperationCellField{ReferenceDomain}, 1}, Nothing}, GridapDistributed.DistributedCellField{MPIArray{Gridap.CellData.OperationCellField{ReferenceDomain}, 1}, Nothing}})`
and a second impelentation as:
`∫(0.5*dt*abs(mean(F⋅n_Γ))*jump(q)*jump(θ))dΓ`
which resulted in the error:
`│    MethodError: no method matching mean(::Gridap.Geometry.SkeletonPair{GridapDistributed.DistributedCellField{MPIArray{Gridap.CellData.OperationCellField{ReferenceDomain}, 1}, Nothing}, GridapDistributed.DistributedCellField{MPIArray{Gridap.CellData.OperationCellField{ReferenceDomain}, 1}, Nothing}})`

**Comment by davelee2804** [comment]
Have implemented upwinding of the potential temperature and potential vorticity in H1 here:
https://github.com/davelee2804/tsw_eigs/commit/df423dc27fc41ac1c84caf421af6ebc294df73a7
These both improve the output somewhat, but do not address the cause of the problem. Still need to figure what is wrong with the interior penalty term, and why this is not effective.

**Comment by davelee2804** [comment]
The reason the interior penalty method is not effective is that the computational mode is not particularly evident in the potential temperature tracer variance, which is what this is damping. See the attached images of the the tracer variance and vertical velocity at time=400s. 
![tracer_var_52x76](https://github.com/davelee2804/tsw_eigs/assets/11448075/6abe053e-1e3c-4d4f-afff-13a76b506b51)
![uy_qup_thetaup_52x76](https://github.com/davelee2804/tsw_eigs/assets/11448075/719b1a71-7cf4-4baa-9184-5d1f2173996f)

Therefore I think the root cause is in the velocity. Will close this issue, and open a new one regarding the upwinding of the mass flux via SUPG for the H(div) velocity.

**Comment by amartinhuertas** [comment]
Hi @davelee2804  ... I got a notification on my mailbox regarding the following comment https://github.com/davelee2804/tsw_eigs/issues/2#issuecomment-1806620363 

However, I see this comment is from a week ago. Do you still want to investigate the alternative ways of defining the interior penalty  term in that function? I can take a look at that at some point.
