### ISSUE TITLE
SUPG upwinding of H(div) vertical mass flux to suppress the computational mode.

### ISSUE THREAD

**Issue by davelee2804** [davelee2804/tsw_eigs#4]
The issue of the computational mode for the L2 potential temperature was described in this previous closed issue:
https://github.com/davelee2804/tsw_eigs/issues/2
In that issue upwinding was added for the H1 potential temperature and potential vorticity, and an interior penalty term was added for the density weighted potential temperature, but none of these suppress the mode effectively.

Since the mode is most evident in the velocity field, a better way to suppress this might be to upwind the H(div) mass flux, `F`, computed as:
`\int v\cdot F d\Omega = \int v\cdot u*h d\Omega` for `v\in H(div)`
For 2D `v = {v_i, v_j) \in H(div)` this could potentially be implemented as `v_i + \tau u_i*dv_i/dx, v_j + \tau u_j*dv_j/dy`, but I'm not sure how to do this yet. Both `dv_i/dx` and `dv_j/dy` should be internally defined somewhere, but I'm not sure where yet.

Note that in order to implement the potential temperature on the vertical component of the H(div) space, as is done in LFRic, access to the vertical H(div) vector component is also required. So similar machinery would also be required in order to compare with LFRic.

**Comment by amartinhuertas** [comment]
Please note that Github supports mathematical notation using Latex. https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/writing-mathematical-expressions

**Comment by amartinhuertas** [comment]
> For 2D v = {v_i, v_j) \in H(div) this could potentially be implemented as v_i + \tau u_i*dv_i/dx, v_j + \tau u_j*dv_j/dy, but I'm not sure how to do this yet. Both dv_i/dx and dv_j/dy should be internally defined somewhere, but I'm not sure where yet.

what about something along these lines (pseudocode, did not try):

```julia
function extract_tensor_diagonal(x::TensorValue{2})
         return TensorValue(x[1,1], zero(eltype(x)), zero(eltype(x)), x[2,2])
end

v + \tau * u \cdot (extract_tensor_diagonal \circ gradient(v))

```

**Comment by davelee2804** [comment]
Thanks for the suggestion @amartinhuertas ! (also, I'd forgotten about latex format in Markdown :)).

What you suggest sounds promising, except that `v` is in `H(div)`, so I think we only have $\nabla\cdot v$ defined, but not $\nabla v$. What I'm looking for is something for $v=(v_i,v_j)\in H(div)$ that returns either $dv_i/dx$ or $dv_j/dy$, as opposed to $\nabla\cdot v = dv_i/dx + dv_j/dy$.

**Comment by amartinhuertas** [comment]
Yes, I am aware of this. 

Mathematically, functions in H(div) are square integrable functions with weak divergence (not weak gradient) square integrable. 

But in the code, it is possible to take the gradient of a function in the RT space and restrict it to the main diagonal.

**Comment by davelee2804** [comment]
OK, great, thanks @amartinhuertas ! I'll take a look at implementing this, and see how I go, thanks for the advice!

**Comment by davelee2804** [comment]
Thanks very much for the help @amartinhuertas . I've tried this out, but it doesn't work, for the understandable reason that:
`∫(dt*(∇⋅(v + dt*(uh⋅(extract_tensor_diagonal∘∇(v)))))*Φ)dΩ`
is attempting to take the divergence of a test function that is no longer div-conforming. So its back to the drawing board. :(

Perhaps the way ahead is to construct an upwinded mass flux, as in equation (2.3.10) in this paper here:
https://www.sciencedirect.com/science/article/abs/pii/S0021999119307223
I will look into this....

**Comment by amartinhuertas** [comment]
> I've tried this out, but it doesn't work, for the understandable reason that:
∫(dt*(∇⋅(v + dt*(uh⋅(extract_tensor_diagonal∘∇(v)))))*Φ)dΩ
is attempting to take the divergence of a test function that is no longer div-conforming. So its back to the drawing board. :(

TBH, I am not so sure what we are trying to do here. Do you have any reference in which this kind of up-winding is discussed? Also I did not know that you were willing to take the divergence of `v + dt*(uh⋅(extract_tensor_diagonal∘∇(v)))`

**Comment by davelee2804** [comment]
Hey @amartinhuertas , what I'm trying to do is suppress the oscillation that is developing (presumably due to the computational mode). The general idea is:
1. Determine a dynamical quantity where the mode initially manifests.
2. Damp that quantity via the application of a symmetric operator that is applied to that quantity (ideally in an energy conserving way, but for now just damping it would be a good first cut).

For a quantity that is continuous across element boundaries (ie the velocity), SUPG would be the first method of choice here. This is what we can do successfully for H1 quantities (ie: the potential vorticity), but not for the H(div) velocity - I hadn't appreciated this earlier.

For a discontinuous quantity where SUPG is ineffective, the idea is to penalise jumps in that quantity. I'm currently looking at $K=\frac{1}{2}u\cdot u$ (see image attached). The idea is to do something similar to what is in this paper 
https://www.sciencedirect.com/science/article/abs/pii/S0021999119307223
in equations (2.3.10) and (2.3.29)
but instead of using `D` as the quantity to penalise (as in that paper for shallow water) to use `K`. I wrote this out last night and I think I know how to do it. I'll let you know how it goes...

![K_52x76](https://github.com/davelee2804/tsw_eigs/assets/11448075/61baa691-498b-4841-85f4-493a4287cae8)

**Comment by amartinhuertas** [comment]
Ok, thanks for the detailed explanations.

**Comment by davelee2804** [comment]
No problem, sorry I've been chopping and changing between different (bad) ideas, pretty confusing I know :) The tricky bit in my limited experience is figuring out which quantity it is you need to damp

**Comment by davelee2804** [comment]
I've created a new branch to explore momentum equation damping as per the above paper.

I'm not sure if this implementation here (for $K=0.5u\cdot u$, not $\rho$:
https://github.com/davelee2804/tsw_eigs/blob/mom_eqn_upwind/src/distributed_euler_flux_solve_eta_implicit_ops.jl#L119
entirely matches the middle term in (2.3.29) of this paper:
https://www.sciencedirect.com/science/article/abs/pii/S0021999119307223

**Comment by amartinhuertas** [comment]
> I've created a new branch to explore momentum equation damping as per the above paper.

Can you open a PR? This will simplify communication among us. Thanks.

**Comment by davelee2804** [comment]
Sure thing, done.

**Comment by amartinhuertas** [comment]
Thanks ... looking now at (2.3.29) and the code that aims to implement the middle term to see if I am able to see something.

**Comment by davelee2804** [comment]
Thanks. I think it is slowly dawning on me that it is not (2.3.29) that is the stabilisation, I think 2.3.29 is just to recover energy conservation. I think it is 2.3.30 that is the cause of the damping. Basically I'm not sure how to implement the upstream flux, what they call $\tilde{D}$. I've been trying to do this as:
`(mean(D) + 0.5*(sign∘((F⋅n_Γ).plus))*jump(D))`
But I'm not sure if that's correct....

**Comment by amartinhuertas** [comment]
Ok ... let me think how we may implement the $\tilde{D}$ field

**Comment by davelee2804** [comment]
...I've been trying to do a Gridap version of (in pseudocode): `mean(D) + sign(F.n)*jump(D)`, but I'm not sure that its implemented correctly

**Comment by amartinhuertas** [comment]
Let us first try to implement the $\tilde{D}$ field ... is it defined in (2.3.2) correct?

**Comment by davelee2804** [comment]
Yes, that's correct.

**Comment by amartinhuertas** [comment]
what about something like ...  did not try it ...

```julia
function alpha(u,n)
   u \cdot n < 0 ? 1.0 : 0.0
end 

alpha \circ (u,n.plus) * D.plus +  (1-alpha \circ (u,n.plus)) * D.minus
 
```

**Comment by davelee2804** [comment]
Yes, that looks good. My current attempt does not look correct. I'm going to sign off but I'll give that a try tomorrow. Thanks for the advice!

**Comment by amartinhuertas** [comment]
yes, me too, good night

**Comment by davelee2804** [comment]
...I tried implementing the above with as:
```
function sgn_un(u,n)
  u⋅n < 0.0 ? 1.0 : 0.0
end
function F_ρ_up!(_Fρ,ρi,ρj,ρh,uh,Q,dΩ,dΓ,n_Γ,dt)
  b(q)    = ∫(q*(ρj - ρi))dΩ +
            ∫(dt*jump((uh⋅n_Γ)*q)*((sgn_un∘(uh,n_Γ.plus))*(ρh.plus) + (1.0 - (sgn_un∘(uh,n_Γ.plus)))*(ρh.minus)))dΓ
  Gridap.FESpaces.assemble_vector!(b,_Fρ,Q)
end
```
But I'm getting an error in the `b(q) = ...` line as:
```
┌ Error:
│   exception =
│    AssertionError: A check failed
│    Stacktrace:
│      [1] macro expansion
│        @ ~/.julia/packages/Gridap/9m0w9/src/Helpers/Macros.jl:60 [inlined]
│      [2] change_domain_ref_ref(........
```

**Comment by amartinhuertas** [comment]
I fixed the error here: https://github.com/davelee2804/tsw_eigs/pull/5/commits/c6837c673a8c47144d790b41b8f9123cb7dfd274

However, it now numerically breakdowns after some time steps. Perhaps there is still something wrong in the current upwinding.

**Comment by davelee2804** [comment]
I've added a continuous interior penalty (CIP) term that effectively suppresses the grid scale velocity noise. More testing could be done once we are able to run at higher resolution once the memory issue is resolved. But for now the CIP term seems to be doing the job, so I'm closing the issue.
